/*** ALERT  */
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const CREATE_EVENT_REQUEST = "CREATE_EVENT_REQUEST";
export const CREATE_EVENT_SUCCESS = "CREATE_EVENT_SUCCESS";
export const CREATE_EVENT_FAIL = "CREATE_EVENT_FAIL";

export const GET_EVENT_REQUEST = "GET_EVENT_REQUEST";
export const GET_EVENT_SUCCESS = "GET_EVENT_SUCCESS";
export const GET_EVENT_FAIL = "GET_EVENT_FAIL";

export const GET_EVENTS_REQUEST = "GET_EVENTS_REQUEST";
export const GET_EVENTS_SUCCESS = "GET_EVENTS_SUCCESS";
export const GET_EVENTS_FAIL = "GET_EVENTS_FAIL";

export const EDIT_EVENT_REQUEST = "EDIT_EVENT_REQUEST";
export const EDIT_EVENT_SUCCESS = "EDIT_EVENT_SUCCESS";
export const EDIT_EVENT_FAIL = "EDIT_EVENT_FAIL";

export const UPLOAD_ATTENDANCE_REQUEST = "UPLOAD_ATTENDANCE_REQUEST";
export const UPLOAD_ATTENDANCE_SUCCESS = "UPLOAD_ATTENDANCE_SUCCESS";
export const UPLOAD_ATTENDANCE_FAIL = "UPLOAD_ATTENDANCE_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";
// -------------------------------

// Add new member
export const ADD_NEW_MEMBER_REQUEST = "ADD_NEW_MEMBER_REQUEST";
export const ADD_NEW_MEMBER_SUCCESS = "ADD_NEW_MEMBER_SUCCESS";
export const ADD_NEW_MEMBER_FAIL = "ADD_NEW_MEMBER_FAIL";
export const RESET_MEMBER_DATA = "RESET_MEMBER_DATA";

export const MEMBERS_UPLOAD_REQUEST = "MEMBERS_UPLOAD_REQUEST";
export const MEMBERS_UPLOAD_SUCCESS = "MEMBERS_UPLOAD_SUCCESS";
export const MEMBERS_UPLOAD_FAIL = "MEMBERS_UPLOAD_FAIL";

export const EDIT_MEMBER_REQUEST = "EDIT_MEMBER_REQUEST";
export const EDIT_MEMBER_SUCCESS = "EDIT_MEMBER_SUCCESS";
export const EDIT_MEMBER_FAIL = "EDIT_MEMBER_FAIL";

// Login
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

// Login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

// User By Auth
export const LOAD_CURRENT_MEMBER_SUCCESS = "LOAD_CURRENT_MEMBER_SUCCESS";
export const LOAD_CURRENT_MEMBER_REQUEST = "LOAD_CURRENT_MEMBER_REQUEST";
export const LOAD_CURRENT_MEMBER_FAIL = "LOAD_CURRENT_MEMBER_FAIL";

// Get Members
export const GET_MEMBERS_SUCCESS = "GET_MEMBERS_SUCCESS";
export const GET_MEMBERS_REQUEST = "GET_MEMBERS_REQUEST";
export const GET_MEMBERS_FAIL = "GET_MEMBERS_FAIL";
// Toggle Admin
export const TOGGLE_ADMIN_SUCCESS = "TOGGLE_ADMIN_SUCCESS";
export const TOGGLE_ADMIN_REQUEST = "TOGGLE_ADMIN_REQUEST";
export const TOGGLE_ADMIN_FAIL = "TOGGLE_ADMIN_FAIL";
// Delete Member
export const DELETE_MEMBER_SUCCESS = "DELETE_MEMBER_SUCCESS";
export const DELETE_MEMBER_REQUEST = "DELETE_MEMBER_REQUEST";
export const DELETE_MEMBER_FAIL = "DELETE_MEMBER_FAIL";

export const LOGOUT = "LOGOUT";
// Profile

export const RESET_PROFILE_DATA = "RESET_PROFILE_DATA";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const ME_PROFILE_SUCCESS = "ME_PROFILE_SUCCESS";
export const ME_PROFILE_REQUEST = "ME_PROFILE_REQUEST";
export const ME_PROFILE_FAIL = "ME_PROFILE_FAIL";

export const GET_PROFILES_SUCCESS = "GET_PROFILES_SUCCESS";
export const GET_PROFILES_REQUEST = "GET_PROFILES_REQUEST";
export const GET_PROFILES_FAIL = "GET_PROFILES_FAIL";

export const PERSONAL_DATA_REQUEST = "PERSONAL_DATA_REQUEST";
export const PERSONAL_DATA_SUCCESS = "PERSONAL_DATA_SUCCESS";
export const PERSONAL_DATA_FAIL = "PERSONAL_DATA_FAIL";

export const NOK_DATA_REQUEST = "NOK_DATA_REQUEST";
export const NOK_DATA_SUCCESS = "NOK_DATA_SUCCESS";
export const NOK_DATA_FAIL = "NOK_DATA_FAIL";

export const CHURCH_DATA_REQUEST = "CHURCH_DATA_REQUEST";
export const CHURCH_DATA_SUCCESS = "CHURCH_DATA_SUCCESS";
export const CHURCH_DATA_FAIL = "CHURCH_DATA_FAIL";

export const UNIT_DATA_REQUEST = "UNIT_DATA_REQUEST";
export const UNIT_DATA_SUCCESS = "UNIT_DATA_SUCCESS";
export const UNIT_DATA_FAIL = "UNIT_DATA_FAIL";

export const DELETE_PROFILES_REQUEST = "DELETE_PROFILES_REQUEST";
export const DELETE_PROFILES_SUCCESS = "DELETE_PROFILES_SUCCESS";
export const DELETE_PROFILES_FAIL = "DELETE_PROFILES_FAIL";

export const MEMBER_IMAGE_REQUEST = "MEMBER_IMAGE_REQUEST";
export const MEMBER_IMAGE_SUCCESS = "MEMBER_IMAGE_SUCCESS";
export const MEMBER_IMAGE_FAIL = "MEMBER_IMAGE_FAIL";

// Send password reset token
export const PASSWORD_TOKEN_REQUEST = "PASSWORD_TOKEN_REQUEST";
export const PASSWORD_TOKEN_SUCCESS = "PASSWORD_TOKEN_SUCCESS";
export const PASSWORD_TOKEN_FAIL = "PASSWORD_TOKEN_FAIL";

// Reset password
export const PASSWORD_RESET_REQUEST = "PASSWORD_RESET_REQUEST";
export const PASSWORD_RESET_SUCCESS = "PASSWORD_RESET_SUCCESS";
export const PASSWORD_RESET_FAIL = "PASSWORD_RESET_FAIL";

export const GET_ACTIVITY_REQUEST = "GET_ACTIVITY_REQUEST";
export const GET_ACTIVITY_SUCCESS = "GET_ACTIVITY_SUCCESS";
export const GET_ACTIVITY_FAIL = "GET_ACTIVITY_FAIL";
