
/******** ALERT  */
export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';

// -------------------------------------------
// Add new member
export const ADD_NEW_MEMBER_REQUEST = 'ADD_NEW_MEMBER_REQUEST';
export const ADD_NEW_MEMBER_SUCCESS = 'ADD_NEW_MEMBER_SUCCESS';
export const ADD_NEW_MEMBER_FAIL = 'ADD_NEW_MEMBER_FAIL';
export const RESET_MEMBER_DATA = 'RESET_MEMBER_DATA';

export const MEMBERS_UPLOAD_REQUEST = 'MEMBERS_UPLOAD_REQUEST';
export const MEMBERS_UPLOAD_SUCCESS = 'MEMBERS_UPLOAD_SUCCESS';
export const MEMBERS_UPLOAD_FAIL = 'MEMBERS_UPLOAD_FAIL';

export const EDIT_MEMBER_REQUEST = 'EDIT_MEMBER_REQUEST';
export const EDIT_MEMBER_SUCCESS = 'EDIT_MEMBER_SUCCESS';
export const EDIT_MEMBER_FAIL = 'EDIT_MEMBER_FAIL';

// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// User By Auth
export const LOAD_CURRENT_MEMBER_SUCCESS = 'LOAD_CURRENT_MEMBER_SUCCESS';
export const LOAD_CURRENT_MEMBER_REQUEST = 'LOAD_CURRENT_MEMBER_REQUEST';
export const LOAD_CURRENT_MEMBER_FAIL = 'LOAD_CURRENT_MEMBER_FAIL';

// Get Members 
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_REQUEST = 'GET_MEMBERS_REQUEST';
export const GET_MEMBERS_FAIL = 'GET_MEMBERS_FAIL';
// Toggle Admin 
export const TOGGLE_ADMIN_SUCCESS = 'TOGGLE_ADMIN_SUCCESS';
export const TOGGLE_ADMIN_REQUEST = 'TOGGLE_ADMIN_REQUEST';
export const TOGGLE_ADMIN_FAIL = 'TOGGLE_ADMIN_FAIL';
// Delete Member
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_REQUEST = 'DELETE_MEMBER_REQUEST';
export const DELETE_MEMBER_FAIL = 'DELETE_MEMBER_FAIL';

export const LOGOUT = 'LOGOUT';
// ------------------------------------------------------------------------
// Profile

export const RESET_PROFILE_DATA = 'RESET_PROFILE_DATA';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL';

export const ME_PROFILE_SUCCESS = 'ME_PROFILE_SUCCESS';
export const ME_PROFILE_REQUEST = 'ME_PROFILE_REQUEST';
export const ME_PROFILE_FAIL = 'ME_PROFILE_FAIL';

export const GET_PROFILES_SUCCESS = 'GET_PROFILES_SUCCESS';
export const GET_PROFILES_REQUEST = 'GET_PROFILES_REQUEST';
export const GET_PROFILES_FAIL = 'GET_PROFILES_FAIL';

export const PERSONAL_DATA_REQUEST = 'PERSONAL_DATA_REQUEST';
export const PERSONAL_DATA_SUCCESS = 'PERSONAL_DATA_SUCCESS';
export const PERSONAL_DATA_FAIL = 'PERSONAL_DATA_FAIL';

export const NOK_DATA_REQUEST = 'NOK_DATA_REQUEST';
export const NOK_DATA_SUCCESS = 'NOK_DATA_SUCCESS';
export const NOK_DATA_FAIL = 'NOK_DATA_FAIL';

export const CHURCH_DATA_REQUEST = 'CHURCH_DATA_REQUEST';
export const CHURCH_DATA_SUCCESS = 'CHURCH_DATA_SUCCESS';
export const CHURCH_DATA_FAIL = 'CHURCH_DATA_FAIL';

export const UNIT_DATA_REQUEST = 'UNIT_DATA_REQUEST';
export const UNIT_DATA_SUCCESS = 'UNIT_DATA_SUCCESS';
export const UNIT_DATA_FAIL = 'UNIT_DATA_FAIL';

export const DELETE_PROFILES_REQUEST = 'DELETE_PROFILES_REQUEST';
export const DELETE_PROFILES_SUCCESS = 'DELETE_PROFILES_SUCCESS';
export const DELETE_PROFILES_FAIL = 'DELETE_PROFILES_FAIL';

export const MEMBER_IMAGE_REQUEST = 'MEMBER_IMAGE_REQUEST';
export const MEMBER_IMAGE_SUCCESS = 'MEMBER_IMAGE_SUCCESS';
export const MEMBER_IMAGE_FAIL = 'MEMBER_IMAGE_FAIL';
// ------------------------------------------------
/********SHILOH */
export const SHILOH_SIGNUP = 'SHILOH_SIGNUP';
export const GET_SHILOH_DATA = 'GET_SHILOH_DATA';
export const UPDATE_SHILOH_DATA = 'UPDATE_SHILOH_DATA';
export const DELETE_SHILOH_DATA = 'DELETE_SHILOH_DATA';
export const RESET_SHILOH_DATA = 'RESET_SHILOH_DATA';
export const GET_SHILOH_ATTENDANCE_LIST = 'GET_SHILOH_ATTENDANCE_LIST';
export const GENERATE_SHILOH_ATTENDANCE_REPORT = 'GENERATE_SHILOH_ATTENDANCE_REPORT';
export const CONFIRM_ACCESS = 'CONFIRM_ACCESS';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const AUTH_FAIL = 'AUTH_FAIL';

export const SEND_PASSWORD_RESET_TOKEN = 'SEND_PASSWORD_RESET_TOKEN';
export const RESET_MEMBER_PASSWORD = 'RESET_MEMBER_PASSWORD';



// export const LOAD_MEMBER_PROFILE = 'LOAD_MEMBER_PROFILE';
// export const CREATE_MEMBER_PROFILE = 'CREATE_MEMBER_PROFILE';
// export const UPDATE_MEMBER_IMAGE = 'UPDATE_MEMBER_IMAGE';
// export const UPDATE_MEMBER_PROFILE = 'UPDATE_MEMBER_PROFILE';
// export const UPDATE_AUTH_DATA = 'UPDATE_AUTH_DATA';
// export const UPDATE_UNIT_INFO = 'UPDATE_UNIT_INFO';
// export const UPDATE_CHURCH_INFO = 'UPDATE_CHURCH_INFO';
// export const UPDATE_NOK_INFO = 'UPDATE_NOK_INFO';
// export const DELETE_PROFILE = 'DELETE_PROFILE';

// Posts
// export const GET_ALL_POSTS = 'GET_ALL_POSTS';
// export const SET_POST_BY_POST_ID = 'SET_POST_BY_POST_ID';
// export const NEW_POST_CREATED = 'NEW_POST_CREATED';
// export const POST_DELETED = 'POST_DELETED';
// export const LIKE_POST = 'LIKE_POST';
// export const UNLIKE_POST = 'UNLIKE_POST';
// export const ADD_COMMENT_TO_POST = 'ADD_COMMENT_TO_POST';
// export const REMOVE_POST_COMMENT = 'REMOVE_POST_COMMENT';


// // Admin
// export const GET_ACCESS = 'GET_ACCESS';
// export const UPLOAD_ACCESS = 'UPLOAD_ACCESS';
// export const ADD_ACCESS = 'ADD_ACCESS';
// export const DELETE_ACCESS = 'DELETE_ACCESS';
// export const FLUSH_ACCESS_LIST = 'FLUSH_ACCESS_LIST';
// export const CLEAR_ACCESS_LIST = 'CLEAR_ACCESS_LIST';
// export const RESET_ACCESS_DATA = 'RESET_ACCESS_DATA';

export const LOAD_MEMBERS = 'LOAD_MEMBERS';
export const GET_MEMBER_PROFILE = 'GET_MEMBER_PROFILE';
export const CLEAR_MEMBER_PROFILE = 'CLEAR_MEMBER_PROFILE';

export const GENERATE_REPORT = 'GENERATE_REPORT';
export const BECOME_ADMIN = 'BECOME_ADMIN';
export const TOGGLE_ADMIN_AUTH = 'TOGGLE_ADMIN_AUTH';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const FLUSH_DATA = 'FLUSH_DATA';



